django>=1.7

# FIXME On later versions I get strange error 'database connection isn't set to UTC'
psycopg2<=2.8.6

pytz; python_version < '3.3'
typing; python_version < '3.5'

# Not required, but should be tested
django-pg-returning

# Linter
flake8
